#! /bin/bash
#this bash script automates the install of go-audit from slack for forwarding logs to rsyslog/file

sudo su
apt-get update && apt-get upgrade -y && apt-get install -y build-essential golang git jq auditd
cd /root

# Update Golang from 1.2 to 1.7 or compilation of go-audit will fail
wget https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz
tar -xvf go1.7.linux-amd64.tar.gz
mv go /usr/local
mkdir ~/.go
export GOROOT=/usr/local/go
export GOPATH=~/.go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
sudo update-alternatives --install "/usr/bin/go" "go" "/usr/local/go/bin/go" 0
sudo update-alternatives --set go /usr/local/go/bin/go

# Download go-audit and its dependencies
go get -u github.com/slackhq/go-audit
go get -u github.com/kardianos/govendor
cd ~/.go/src/github.com/slackhq/go-audit/

# Build go-audit
make
cp go-audit.yaml.example go-audit.yaml

#use to be
# use this also


#wget https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz
#tar -C /usr/local -xzf go1.7.4.linux-amd64.tar.gz

# Add it to our path
#echo -e "export PATH=$PATH:/usr/local/go/bin" >> /etc/profile
#source /etc/profile

# Ensure we're running at least go 1.7
#go version
# Returns: go version go1.7.4 linux/amd64

# Set our GOPATH to ~/go
#mkdir ~/go
#export GOPATH=~/go
#apt-get install build-essential
#go get -u github.com/kardianos/govendor

#cd  go/src/
#git clone https://github.com/slackhq/go-audit.git
#cd go-audit
#~/go/bin/govendor sync  # This command takes a while with no output
#go build
